### ISSUE TITLE
Is URL correct?

### ISSUE THREAD

**Issue by vicperdana** [preezie-yasir/dotnet8-http-error#1]
Hey @preezie-yasir is this URL correct?
I got `400 Bad Request`

https://github.com/preezie-yasir/dotnet8-http-error/blob/755e2d88bb6efe6ba5359b241218b3b0dced2555/Dotnet8.Http.Test/Dotnet8.Http.Test/Program.cs#L15

Removing `"` resulted in successful download

**Comment by vicperdana** [comment]
Got this too when running locally

```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Program.<>c.<<<Main>$>b__0_0>d.MoveNext() in /Users/vicperdana/coderepo/demos/dotnet8-http-error/Dotnet8.Http.Test/Dotnet8.Http.Test/Program.cs:line 27
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
 ```

**Comment by preezie-yasir** [comment]
Hi @vicperdana sorry there must have been a copying error between mac and the IDE for some odd reason. I've fixed the url however, It's still failing in azure.

**Comment by preezie-yasir** [comment]
> Got this too when running locally
> 
> ```
> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
>       An unhandled exception has occurred while executing the request.
>       System.NullReferenceException: Object reference not set to an instance of an object.
>          at Program.<>c.<<<Main>$>b__0_0>d.MoveNext() in /Users/vicperdana/coderepo/demos/dotnet8-http-error/Dotnet8.Http.Test/Dotnet8.Http.Test/Program.cs:line 27
>       --- End of stack trace from previous location ---
>          at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
>          at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
> ```

This should also be fixed with my most recent commit. Just added some nullable checks
